version: "3"

services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: 'workshopserver'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links:
      - psql
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  psql:
    build:
      context: "./bin/${PSQL}"
    container_name: 'workshoppsql'
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
      PGPASSWORD: ${PSQL_PGPASSWORD}
    volumes:
      - ${PSQL_DATA_DIR-./data/psql}:/var/lib/postgresql
      - ${PSQL_LOG_DIR-./logs/psql}:/var/log/postgresql
    ports:
      - "54322:5432"
    restart: always

